Fixes to get project working with docker compose (rather than docker-compose)
Slight importer tweaks because of issues getting ps extensions to work
Specify numpy version because of python ValueError

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject